#!/bin/sh
# run this file to initiate the Autoconf chain, turning *.AM into *.in for your configure
# based on the autoconf simple file from ogre3d.org 'Homble Beginnings' project
set -x
rm -rf config.cache autom4te.cache
libtoolize --force --copy && \
aclocal && \
autoheader && \
automake --add-missing --force-missing --copy --foreign && \
autoconf
